# Generated by Django 6.0.3 on 2026-04-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('one_time', 'One-Time Purchase'), ('subscription_monthly', 'Monthly Subscription'), ('subscription_annual', 'Annual Subscription')], default='one_time', max_length=30),
        ),
    ]
