# Generated by Django 6.0.3 on 2026-04-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRealityIndexSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text="e.g. 'April 2026'", max_length=20)),
                ('month_date', models.DateField(help_text='First day of the month — used for ordering', unique=True)),
                ('salary_pressure', models.PositiveSmallIntegerField(help_text='% of submissions reporting stagnant/declining CTC')),
                ('switch_difficulty', models.PositiveSmallIntegerField(help_text='Index of switching friction based on notice + bond signals')),
                ('layoff_risk', models.PositiveSmallIntegerField(help_text='% of layoff reports (freeze/rumor/layoff) in last 30 days')),
                ('overall', models.PositiveSmallIntegerField(help_text='Composite score — weighted average of the three signals')),
                ('total_salary_submissions', models.PositiveIntegerField(default=0)),
                ('total_layoff_reports', models.PositiveIntegerField(default=0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Career Reality Index Snapshot',
                'verbose_name_plural': 'Career Reality Index Snapshots',
                'ordering': ['-month_date'],
            },
        ),
    ]
