# Generated by Django 6.0.3 on 2026-04-06 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro — ₹299/month'), ('team', 'Team — ₹999/month')], default='free', max_length=20)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('salary_submissions_count', models.PositiveIntegerField(default=0)),
                ('assessments_count', models.PositiveIntegerField(default=0)),
                ('last_risk_level', models.CharField(blank=True, max_length=20)),
                ('last_company_type', models.CharField(blank=True, max_length=50)),
                ('newsletter_subscribed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
