# Generated by Django 6.0.3 on 2026-04-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='salary_credits',
            field=models.PositiveIntegerField(default=0, help_text='Credits earned by submitting salary data. 1 credit = unlock 1 salary record.'),
        ),
    ]
