# Generated by Django 6.1 on 2026-08-12 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_watchlist'),
        ('companies', '0002_phase1_data_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisor_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvisorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('citations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.advisorconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('layoff', 'Layoff Risk'), ('freeze', 'Hiring Freeze'), ('salary_stagnation', 'Salary Stagnation'), ('ai_disruption', 'AI Disruption'), ('industry_decline', 'Industry Decline')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('source_url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('experience_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('company_type', models.CharField(blank=True, choices=[('service', 'IT Services'), ('product', 'Product Company'), ('mnc_captive', 'MNC Captive / GCC'), ('startup', 'Startup'), ('small_indian', 'Small Indian Firm'), ('unicorn', 'Unicorn / Big Tech')], max_length=20)),
                ('current_ctc', models.IntegerField(blank=True, help_text='Annual CTC in lakhs', null=True)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('ctc', models.IntegerField(help_text='Annual CTC in lakhs')),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('salary_percentile', models.IntegerField(blank=True, null=True)),
                ('peer_comparison', models.CharField(blank=True, choices=[('ahead', 'Ahead of peers'), ('on_track', 'On track'), ('behind', 'Falling behind')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('label', models.CharField(default='Offer', max_length=50)),
                ('company_name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=100)),
                ('ctc', models.IntegerField()),
                ('fixed_pct', models.IntegerField(default=70)),
                ('variable_pct', models.IntegerField(default=10)),
                ('esop_value', models.IntegerField(default=0)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('commute_minutes', models.IntegerField(blank=True, null=True)),
                ('work_mode', models.CharField(choices=[('office', 'Office'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], default='hybrid', max_length=20)),
                ('wlb_rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
