# Generated by Django 5.2.9 on 2026-02-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AITag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'AI Tag',
                'verbose_name_plural': 'AI Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AINewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('summary', models.TextField(help_text='2-3 sentence editorial summary of the development.')),
                ('career_angle', models.TextField(blank=True, help_text='What this means for your career. The Career Reality editorial overlay.')),
                ('source_name', models.CharField(help_text='e.g., OpenAI, VentureBeat, DeepMind', max_length=100)),
                ('source_url', models.URLField(help_text='Link to the original article/announcement.', max_length=500)),
                ('significance', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='Editorial importance rating.', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('external_id', models.CharField(blank=True, help_text='RSS entry guid or API id for deduplication.', max_length=500, null=True, unique=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='news_items', to='ainews.aitag')),
            ],
            options={
                'verbose_name': 'AI News Item',
                'verbose_name_plural': 'AI News Items',
                'ordering': ['-published_at'],
            },
        ),
    ]
