# Generated by Django 5.2.9 on 2026-02-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ainews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AINewsFetchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='success', max_length=20)),
                ('total_created', models.PositiveIntegerField(default=0)),
                ('total_skipped', models.PositiveIntegerField(default=0)),
                ('total_warnings', models.PositiveIntegerField(default=0)),
                ('total_errors', models.PositiveIntegerField(default=0)),
                ('source_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'AI News Fetch Run',
                'verbose_name_plural': 'AI News Fetch Runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='ainewsitem',
            name='event_date',
            field=models.DateTimeField(blank=True, help_text='Date when the external event/release happened.', null=True),
        ),
        migrations.AddField(
            model_name='ainewsitem',
            name='fact_check_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('verified', 'Verified')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='ainewsitem',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ainewsitem',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ainewsitem',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Latest editorial review/update timestamp.', null=True),
        ),
        migrations.AddField(
            model_name='ainewsitem',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
