# Generated by Django 5.2.9 on 2026-03-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ainews', '0002_ainewsfetchrun_ainewsitem_event_date_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ainewsitem',
            index=models.Index(fields=['status', '-published_at'], name='ainews_status_pubdate_idx'),
        ),
        migrations.AddIndex(
            model_name='ainewsitem',
            index=models.Index(fields=['status', '-reviewed_at'], name='ainews_status_reviewed_idx'),
        ),
    ]
