# Generated by Django 6.0.3 on 2026-03-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ainews', '0003_performance_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ainewsitem',
            index=models.Index(fields=['status', '-event_date', '-published_at'], name='ainews_status_event_pub_idx'),
        ),
    ]
