"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlsplit
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env for local development. In production (Vercel) env vars are injected
# directly by the platform so this is a no-op there (file won't exist).
# Never overrides variables already set in the shell environment.
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env', override=False)
except ImportError:
    pass  # python-dotenv not installed — rely on env vars being set externally


def _csv_env(name: str, default: str = "") -> list[str]:
    raw = os.environ.get(name, default)
    return [x.strip() for x in raw.split(",") if x.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False for safety. Explicitly set DEBUG=True in local .env.
DEBUG = os.environ.get('DEBUG', 'False') == 'True'
if DEBUG:
    SECRET_KEY = os.environ.get('SECRET_KEY') or get_random_secret_key()
else:
    SECRET_KEY = os.environ.get('SECRET_KEY')
CANONICAL_BASE_URL = os.environ.get("CANONICAL_BASE_URL", "https://www.careerreality.in").strip().rstrip("/")
CANONICAL_HOST = urlsplit(CANONICAL_BASE_URL).netloc.lower()

# E-E-A-T: external profiles for Organization/WebSite schema sameAs (comma-separated URLs).
SITE_SOCIAL_PROFILES = _csv_env("SITE_SOCIAL_PROFILES")
GA_MEASUREMENT_ID = os.environ.get("GA_MEASUREMENT_ID", "").strip()

# Performance tuning (seconds).
SITEMAP_CACHE_TIMEOUT = int(os.environ.get("SITEMAP_CACHE_TIMEOUT", "21600"))
SOCIAL_PROOF_CACHE_TIMEOUT = int(os.environ.get("SOCIAL_PROOF_CACHE_TIMEOUT", "1800"))
INDEX_ROWS_CACHE_TIMEOUT = int(os.environ.get("INDEX_ROWS_CACHE_TIMEOUT", "3600"))
PAGE_CACHE_ARTICLE_SECONDS = int(os.environ.get("PAGE_CACHE_ARTICLE_SECONDS", "3600"))
PAGE_CACHE_HOME_SECONDS = int(os.environ.get("PAGE_CACHE_HOME_SECONDS", "3600"))

if DEBUG:
    ALLOWED_HOSTS = _csv_env("ALLOWED_HOSTS", "127.0.0.1,localhost,testserver")
else:
    ALLOWED_HOSTS = _csv_env("ALLOWED_HOSTS")
    vercel_url = os.environ.get("VERCEL_URL", "").strip()
    if vercel_url:
        ALLOWED_HOSTS.append(vercel_url)

# Always allow the canonical domains (but NOT wildcard *.vercel.app).
for host in [".careerreality.in", "careerreality.in", "www.careerreality.in"]:
    if host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)

default_csrf_origins = [
    "https://careerreality.in",
    "https://www.careerreality.in",
]
CSRF_TRUSTED_ORIGINS = _csv_env("CSRF_TRUSTED_ORIGINS", ",".join(default_csrf_origins))
if DEBUG:
    CSRF_TRUSTED_ORIGINS.extend(["http://127.0.0.1:8000", "http://localhost:8000"])
vercel_url = os.environ.get("VERCEL_URL", "").strip()
if vercel_url:
    vercel_origin = f"https://{vercel_url}"
    if vercel_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(vercel_origin)

# Use signed cookies for sessions to avoid writing to read-only DB on Vercel
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"


# Application definition

INSTALLED_APPS = [
    'whitenoise.runserver_nostatic', # Enable Whitenoise in Dev
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for sitemaps
    'django.contrib.sitemaps', # Required for sitemaps
    'core',
    'content',
    'analyzer',
    'ainews',
    # --- Revenue Layer ---
    'accounts',
    'payments',
    # --- Intelligence Layer ---
    'companies',
    'search',
    # --- Auth ---
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.CanonicalHostRedirectMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Serve static files before GZip (avoids double-compression)
    'django.middleware.gzip.GZipMiddleware', # Compress HTML/JSON responses from Django views
    'core.middleware.SecurityHeadersMiddleware',
    'core.middleware.EdgeCacheHeadersMiddleware',
    'core.middleware.RequestObservabilityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

template_options = {
    'context_processors': [
        'django.template.context_processors.request',
        'django.contrib.auth.context_processors.auth',
        'django.contrib.messages.context_processors.messages',
        'core.context_processors.seo_defaults',
        'core.context_processors.seo_internal_links',
        'core.context_processors.salary_credits_context',
    ],
}
if not DEBUG:
    template_options['loaders'] = [
        (
            'django.template.loaders.cached.Loader',
            [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
        )
    ]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': DEBUG,
        'OPTIONS': template_options,
    },
]

# Security hardening defaults for production-like environments.
if not DEBUG:
    if not SECRET_KEY:
        raise RuntimeError("SECRET_KEY must be set in production.")
    if not ALLOWED_HOSTS:
        raise RuntimeError("ALLOWED_HOSTS must be set in production.")

    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True') == 'True'
    SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'True') == 'True'
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    X_FRAME_OPTIONS = 'DENY'
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# IMPORTANT: SQLite is NOT supported on Vercel. Use PostgreSQL via DATABASE_URL.

import dj_database_url

# Prefer DATABASE_URL as canonical; fall back to POSTGRES_URL for backward compatibility.
DATABASE_URL = os.environ.get('DATABASE_URL') or os.environ.get('POSTGRES_URL')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=int(os.environ.get('DB_CONN_MAX_AGE', '600')),
            conn_health_checks=True,
            ssl_require=True
        )
    }
else:
    # Local development fallback - SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Cache: use Redis in production (required for shared state across Vercel
# serverless instances). Falls back to locmem for local development only.
_REDIS_URL = os.environ.get('REDIS_URL') or os.environ.get('KV_URL')
_CACHE_TIMEOUT = int(os.environ.get('CACHE_TIMEOUT_SECONDS', '300'))

if _REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _REDIS_URL,
            'TIMEOUT': _CACHE_TIMEOUT,
            # Bump to invalidate stale cache_page HTML after template deploys.
            'KEY_PREFIX': os.environ.get('CACHE_KEY_PREFIX', 'cr-tools-v2'),
        }
    }
elif not DEBUG:
    import logging as _logging
    _logging.getLogger(__name__).warning(
        "REDIS_URL not set in production — page cache will NOT persist across "
        "Vercel serverless instances. Set REDIS_URL for sub-second TTFB."
    )
else:
    # Local development fallback only — NOT suitable for multi-process/serverless.
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'career-reality-cache',
            'TIMEOUT': _CACHE_TIMEOUT,
            'OPTIONS': {
                'MAX_ENTRIES': int(os.environ.get('CACHE_MAX_ENTRIES', '5000')),
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

from django.utils.translation import gettext_lazy as _
LANGUAGES = [
    ('en', _('English')),
    ('hi', _('Hindi')),
]
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise Configuration
if not DEBUG:
    # Production: Use Manifest for hashing and long-term caching
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    WHITENOISE_MAX_AGE = int(os.environ.get('WHITENOISE_MAX_AGE', '31536000'))
else:
    # Development: No manifest needed, just serving
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging: structured console output captured by Vercel / stdout.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# ---------------------------------------------------------------------------
# Revenue Layer — API Keys (all optional, graceful fallback if missing)
# ---------------------------------------------------------------------------

# Razorpay — https://dashboard.razorpay.com/app/keys
RAZORPAY_KEY_ID = os.environ.get("RAZORPAY_KEY_ID", "")
RAZORPAY_KEY_SECRET = os.environ.get("RAZORPAY_KEY_SECRET", "")
RAZORPAY_WEBHOOK_SECRET = os.environ.get("RAZORPAY_WEBHOOK_SECRET", "")

# Resend — https://resend.com/api-keys
RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "")
FROM_EMAIL = os.environ.get("FROM_EMAIL", "Career Reality <hello@careerreality.in>")

# OpenAI — https://platform.openai.com/api-keys
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")

# ---------------------------------------------------------------------------
# django-allauth — Google OAuth
# ---------------------------------------------------------------------------
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# allauth v0.63+ API
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_ADAPTER = "accounts.adapter.AccountAdapter"
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/pro/dashboard/"
LOGOUT_REDIRECT_URL = "/"

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        "OAUTH_PKCE_ENABLED": True,
        "APP": {
            "client_id": os.environ.get("GOOGLE_CLIENT_ID", ""),
            "secret": os.environ.get("GOOGLE_CLIENT_SECRET", ""),
            "key": "",
        },
    }
}

SOCIALACCOUNT_AUTO_SIGNUP = True
