"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlsplit

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _csv_env(name: str, default: str = "") -> list[str]:
    raw = os.environ.get(name, default)
    return [x.strip() for x in raw.split(",") if x.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEV_FALLBACK_SECRET = 'cr-local-fallback-9N2vL6qP3xR8mT1cW5yK7dF4hB0zQ9eA2sU6jM8nC3'
SECRET_KEY = os.environ.get('SECRET_KEY', DEV_FALLBACK_SECRET)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False for safety. Explicitly set DEBUG=True in local .env.
DEBUG = os.environ.get('DEBUG', 'False') == 'True'
CANONICAL_BASE_URL = os.environ.get("CANONICAL_BASE_URL", "https://www.careerreality.in").strip().rstrip("/")
CANONICAL_HOST = urlsplit(CANONICAL_BASE_URL).netloc.lower()

if DEBUG:
    ALLOWED_HOSTS = _csv_env("ALLOWED_HOSTS", "127.0.0.1,localhost,testserver")
else:
    ALLOWED_HOSTS = _csv_env("ALLOWED_HOSTS")
    vercel_url = os.environ.get("VERCEL_URL", "").strip()
    if vercel_url:
        ALLOWED_HOSTS.append(vercel_url)

# Always allow the canonical domains.
for host in [".vercel.app", ".careerreality.in", "careerreality.in", "www.careerreality.in"]:
    if host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)

default_csrf_origins = [
    "https://careerreality.in",
    "https://www.careerreality.in",
]
CSRF_TRUSTED_ORIGINS = _csv_env("CSRF_TRUSTED_ORIGINS", ",".join(default_csrf_origins))
if DEBUG:
    CSRF_TRUSTED_ORIGINS.extend(["http://127.0.0.1:8000", "http://localhost:8000"])
vercel_url = os.environ.get("VERCEL_URL", "").strip()
if vercel_url:
    vercel_origin = f"https://{vercel_url}"
    if vercel_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(vercel_origin)

# Use signed cookies for sessions to avoid writing to read-only DB on Vercel
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"


# Application definition

INSTALLED_APPS = [
    'whitenoise.runserver_nostatic', # Enable Whitenoise in Dev
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for sitemaps
    'django.contrib.sitemaps', # Required for sitemaps
    'core',
    'content',
    'analyzer',
    'ainews',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.CanonicalHostRedirectMiddleware',
    'django.middleware.gzip.GZipMiddleware', # Added for HTML compression
    'whitenoise.middleware.WhiteNoiseMiddleware', # Added WhiteNoise
    'core.middleware.SecurityHeadersMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

template_options = {
    'context_processors': [
        'django.template.context_processors.request',
        'django.contrib.auth.context_processors.auth',
        'django.contrib.messages.context_processors.messages',
        'core.context_processors.seo_defaults',
    ],
}
if not DEBUG:
    template_options['loaders'] = [
        (
            'django.template.loaders.cached.Loader',
            [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
        )
    ]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': DEBUG,
        'OPTIONS': template_options,
    },
]

# Security hardening defaults for production-like environments.
if not DEBUG:
    if SECRET_KEY == DEV_FALLBACK_SECRET:
        raise RuntimeError("SECRET_KEY must be set in production.")
    if not ALLOWED_HOSTS:
        raise RuntimeError("ALLOWED_HOSTS must be set in production.")

    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True') == 'True'
    SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'True') == 'True'
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    X_FRAME_OPTIONS = 'DENY'
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
    SECURE_BROWSER_XSS_FILTER = True

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# IMPORTANT: SQLite is NOT supported on Vercel. Use PostgreSQL via DATABASE_URL.

import dj_database_url

# Prefer DATABASE_URL as canonical; fall back to POSTGRES_URL for backward compatibility.
DATABASE_URL = os.environ.get('DATABASE_URL') or os.environ.get('POSTGRES_URL')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=int(os.environ.get('DB_CONN_MAX_AGE', '600')),
            conn_health_checks=True,
            ssl_require=True
        )
    }
else:
    # Local development fallback - SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Cache: use Redis in production (required for shared state across Vercel
# serverless instances). Falls back to locmem for local development only.
_REDIS_URL = os.environ.get('REDIS_URL') or os.environ.get('KV_URL')
_CACHE_TIMEOUT = int(os.environ.get('CACHE_TIMEOUT_SECONDS', '300'))

if _REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _REDIS_URL,
            'TIMEOUT': _CACHE_TIMEOUT,
        }
    }
else:
    # Local development fallback only — NOT suitable for multi-process/serverless.
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'career-reality-cache',
            'TIMEOUT': _CACHE_TIMEOUT,
            'OPTIONS': {
                'MAX_ENTRIES': int(os.environ.get('CACHE_MAX_ENTRIES', '5000')),
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

from django.utils.translation import gettext_lazy as _
LANGUAGES = [
    ('en', _('English')),
    ('hi', _('Hindi')),
]
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise Configuration
if not DEBUG:
    # Production: Use Manifest for hashing and long-term caching
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    WHITENOISE_MAX_AGE = int(os.environ.get('WHITENOISE_MAX_AGE', '31536000'))
    WHITENOISE_IMMUTABLE_FILE_TEST = lambda path, url: url.startswith('/static/')
else:
    # Development: No manifest needed, just serving
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging: structured console output captured by Vercel / stdout.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
