# Generated by Django 6.0.3 on 2026-04-06 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('logo_url', models.URLField(blank=True, help_text='URL to company logo (Clearbit/brand)')),
                ('website', models.URLField(blank=True)),
                ('sector', models.CharField(choices=[('service', 'IT Services / Consulting'), ('product', 'Product Company'), ('startup', 'Startup (< 3 years)'), ('unicorn', 'Unicorn / Big Tech'), ('mnc_captive', 'MNC Captive Centre'), ('bfsi', 'BFSI / Fintech'), ('ecommerce', 'E-Commerce'), ('edtech', 'EdTech'), ('healthtech', 'HealthTech'), ('other', 'Other')], db_index=True, max_length=30)),
                ('size', models.CharField(blank=True, choices=[('1-50', '1–50 employees'), ('51-200', '51–200 employees'), ('201-1000', '201–1,000 employees'), ('1001-5000', '1,001–5,000 employees'), ('5001-10000', '5,001–10,000 employees'), ('10001+', '10,001+ employees')], max_length=20)),
                ('headquarters', models.CharField(blank=True, help_text='e.g. Bangalore, India', max_length=100)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Brief company description')),
                ('work_mode', models.CharField(blank=True, choices=[('office', 'Office-first'), ('hybrid', 'Hybrid'), ('remote', 'Remote-first')], max_length=20)),
                ('glassdoor_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('ambitionbox_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('avg_ctc', models.IntegerField(blank=True, help_text='Average CTC from submissions', null=True)),
                ('salary_count', models.PositiveIntegerField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('layoff_report_count', models.PositiveIntegerField(default=0)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=1, help_text='Composite score 0-10 based on salary, culture, stability', max_digits=3, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Manually verified by editorial team')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-salary_count', 'name'],
                'indexes': [models.Index(fields=['sector', '-salary_count'], name='companies_c_sector_263068_idx'), models.Index(fields=['-overall_score'], name='companies_c_overall_08d834_idx'), models.Index(fields=['name'], name='companies_c_name_2d8260_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=100)),
                ('role_level', models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior (0–2 yrs)'), ('mid', 'Mid (3–5 yrs)'), ('senior', 'Senior (6–10 yrs)'), ('lead', 'Lead / Manager'), ('director', 'Director+')], max_length=20)),
                ('employment_status', models.CharField(choices=[('current', 'Current Employee'), ('former', 'Former Employee')], max_length=20)),
                ('tenure_months', models.PositiveIntegerField(help_text='Months at company')),
                ('rating_overall', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('rating_salary', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('rating_culture', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('rating_growth', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('rating_worklife', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('rating_management', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('pros', models.TextField(help_text="What's good about working here?")),
                ('cons', models.TextField(help_text="What's bad? Be honest.")),
                ('advice_to_management', models.TextField(blank=True)),
                ('would_rejoin', models.BooleanField(help_text='Would you join this company again?')),
                ('biggest_lie', models.CharField(blank=True, help_text='What did the company promise but never delivered?', max_length=300)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False, help_text='Flagged for moderation')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='companies_c_company_c4b335_idx'), models.Index(fields=['company', 'rating_overall'], name='companies_c_company_38c648_idx')],
            },
        ),
    ]
