# Generated by Django 6.0.3 on 2026-04-13 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_handle', models.CharField(blank=True, max_length=50)),
                ('topic', models.CharField(choices=[('salary', 'Salary & Compensation'), ('culture', 'Work Culture'), ('layoff', 'Layoffs & Stability'), ('switching', 'Job Switching'), ('career', 'Career Growth'), ('interview', 'Interview Experience'), ('wlb', 'Work-Life Balance'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='The full question or discussion post')),
                ('role', models.CharField(blank=True, help_text='e.g. Senior Engineer at a product company', max_length=100)),
                ('upvotes', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Company this discussion is about (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to='companies.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_handle', models.CharField(blank=True, max_length=50)),
                ('body', models.TextField()),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='companies.discussion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['company', '-created_at'], name='companies_d_company_355528_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['topic', '-upvotes'], name='companies_d_topic_616d51_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['-upvotes', '-created_at'], name='companies_d_upvotes_4ea209_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionreply',
            index=models.Index(fields=['discussion', 'created_at'], name='companies_d_discuss_38444c_idx'),
        ),
    ]
