# Generated by Django 6.1 on 2026-08-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_phase1_data_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='reality_score_json',
            field=models.JSONField(blank=True, help_text='Cached dimension breakdown for Company Reality Score', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='reality_score_overall',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Denormalized Company Reality Score 0-10', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='reality_score_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
