# Generated by Django 5.2.9 on 2025-12-22 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Real human name (Proof of life)', max_length=100)),
                ('display_name', models.CharField(help_text='Public brand-safe name', max_length=100)),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='authors/')),
                ('linkedin_url', models.URLField(help_text='Critical Trust Signal')),
                ('experience_summary', models.CharField(blank=True, help_text="e.g. '10+ years in Fintech Product Management'", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0 = first)')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('target_persona', models.CharField(help_text='Who is this specific article for?', max_length=255)),
                ('who_should_avoid', models.TextField(help_text='Trust Signal: Who should NOT pursue this?')),
                ('common_expectation', models.TextField(help_text='The Myth / What people think')),
                ('actual_reality', models.TextField(help_text="The Truth / What it's actually like")),
                ('salary_reality', models.TextField(help_text='Real data tables/ranges. No hype.')),
                ('stuck_point', models.TextField(help_text='Where most people fail or plateau')),
                ('verdict', models.TextField(help_text='Final honest conclusion')),
                ('meta_title', models.CharField(help_text='SEO Title (max 60 chars)', max_length=60)),
                ('meta_description', models.CharField(help_text='SEO Description (max 160 chars)', max_length=160)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_reality_check', models.DateField(blank=True, help_text='Date of last factual review', null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.category')),
            ],
        ),
    ]
