# Generated by Django 5.2.9 on 2025-12-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='target_persona',
            field=models.TextField(help_text='Who is this specific article for?'),
        ),
    ]
