# Generated by Django 5.2.9 on 2026-02-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_article_target_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='actual_reality_hi',
            field=models.TextField(blank=True, help_text='Hindi Translation', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='common_expectation_hi',
            field=models.TextField(blank=True, help_text='Hindi Translation', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description_hi',
            field=models.CharField(blank=True, help_text='Hindi Translation', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title_hi',
            field=models.CharField(blank=True, help_text='Hindi Translation', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='salary_reality_hi',
            field=models.TextField(blank=True, help_text='Hindi Translation', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='stuck_point_hi',
            field=models.TextField(blank=True, help_text='Hindi Translation', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='target_persona_hi',
            field=models.TextField(blank=True, help_text='Hindi Translation', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_hi',
            field=models.CharField(blank=True, help_text='Hindi Translation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='verdict_hi',
            field=models.TextField(blank=True, help_text='Hindi Translation', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='who_should_avoid_hi',
            field=models.TextField(blank=True, help_text='Hindi Translation', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_hi',
            field=models.TextField(blank=True, help_text='Hindi Translation', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hi',
            field=models.CharField(blank=True, help_text='Hindi Translation', max_length=100, null=True),
        ),
    ]
