# Generated by Django 5.2.9 on 2026-03-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_article_actual_reality_hi_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-published_at'], name='article_status_pubdate_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'category', '-published_at'], name='article_status_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-updated_at'], name='article_status_updated_idx'),
        ),
    ]
