# Generated by Django 6.0.3 on 2026-04-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='article_status_pubdate_idx',
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='article_status_cat_idx',
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='article_status_updated_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_hi',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_hi',
        ),
        migrations.RemoveField(
            model_name='article',
            name='actual_reality_hi',
        ),
        migrations.RemoveField(
            model_name='article',
            name='common_expectation_hi',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_description_hi',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_title_hi',
        ),
        migrations.RemoveField(
            model_name='article',
            name='salary_reality_hi',
        ),
        migrations.RemoveField(
            model_name='article',
            name='stuck_point_hi',
        ),
        migrations.RemoveField(
            model_name='article',
            name='target_persona_hi',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_hi',
        ),
        migrations.RemoveField(
            model_name='article',
            name='verdict_hi',
        ),
        migrations.RemoveField(
            model_name='article',
            name='who_should_avoid_hi',
        ),
    ]
