# Generated by Django 5.2.9 on 2025-12-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(help_text='Calculated Risk (Low/Medium/High)', max_length=20)),
                ('scenario_type', models.CharField(help_text='Primary driver (e.g. manager_pressure)', max_length=100)),
                ('has_offer', models.BooleanField(default=False)),
                ('tool_version', models.CharField(default='v1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
