# Generated by Django 5.2.9 on 2026-01-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='e.g. Senior Backend Engineer', max_length=100)),
                ('experience_years', models.FloatField(help_text='Years of Experience')),
                ('company_type', models.CharField(choices=[('service', 'Service Based (TCS/Infy/Wipro)'), ('product', 'Product Based (Swiggy/Zomato/Flipkart)'), ('startup', 'Early Stage Startup'), ('unicorn', 'Unicorn / Big Tech')], max_length=20)),
                ('ctc', models.IntegerField(help_text='Annual CTC in INR')),
                ('in_hand', models.IntegerField(blank=True, help_text='Monthly In-Hand (Optional)', null=True)),
                ('city', models.CharField(max_length=50)),
                ('tech_stack', models.CharField(blank=True, help_text='e.g. Java, React, AWS', max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
