# Generated by Django 5.2.9 on 2026-01-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_salarysubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoffReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('hiring', 'Hiring Aggressively (Safe)'), ('freeze', 'Hiring Freeze'), ('rumor', 'Rumors of Layoffs'), ('layoff', 'Active Layoffs (Danger)')], max_length=20)),
                ('role_affected', models.CharField(blank=True, help_text='e.g. Sales, Engineering', max_length=100)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('details', models.TextField(blank=True, help_text='Context (optional)')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
