# Generated by Django 6.0.3 on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_alter_assessmentlog_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunnelEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(choices=[('landing_view', 'Landing View'), ('analyze_submit', 'Analyze Submit'), ('analysis_rendered', 'Analysis Rendered'), ('paywall_view', 'Paywall View'), ('upgrade_click', 'Upgrade Click'), ('upgrade_success', 'Upgrade Success'), ('return_visit_d7', 'Return Visit D7')], db_index=True, max_length=40)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('page_path', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
