# Generated by Django 6.0.3 on 2026-04-13 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_funneleventlog'),
        ('companies', '0002_phase1_data_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoffreport',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Linked company profile (if matched)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layoff_reports', to='companies.company'),
        ),
        migrations.AddField(
            model_name='salarysubmission',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Linked company profile (if matched)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_submissions', to='companies.company'),
        ),
        migrations.AddField(
            model_name='salarysubmission',
            name='company_name',
            field=models.CharField(blank=True, help_text='Raw company name as entered by user', max_length=150),
        ),
        migrations.AddIndex(
            model_name='layoffreport',
            index=models.Index(fields=['company', '-created_at'], name='analyzer_la_company_d54531_idx'),
        ),
        migrations.AddIndex(
            model_name='layoffreport',
            index=models.Index(fields=['status', '-created_at'], name='analyzer_la_status_bbf7f5_idx'),
        ),
        migrations.AddIndex(
            model_name='salarysubmission',
            index=models.Index(fields=['company', '-created_at'], name='analyzer_sa_company_f6f0bc_idx'),
        ),
        migrations.AddIndex(
            model_name='salarysubmission',
            index=models.Index(fields=['role', '-ctc'], name='analyzer_sa_role_e39da9_idx'),
        ),
        migrations.AddIndex(
            model_name='salarysubmission',
            index=models.Index(fields=['city', '-ctc'], name='analyzer_sa_city_1cf0b1_idx'),
        ),
    ]
